# Generated by Django 5.2 on 2026-05-31 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas_vendas', '0002_assinatura_eh_teste_gratis_alter_assinatura_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinatura',
            name='asaas_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assinatura',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('cancelado', 'Cancelado'), ('expirado', 'Expirado'), ('teste', 'Teste Gratuito'), ('pendente', 'Pendente')], max_length=20),
        ),
        migrations.AlterField(
            model_name='assinatura',
            name='validade',
            field=models.DateTimeField(),
        ),
    ]
