# Generated by Django 5.2 on 2026-06-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas_vendas', '0004_assinatura_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text='Usado na URL de checkout, ex: 1-mes', unique=True)),
                ('descricao', models.TextField(blank=True, help_text='Descrição do plano e/ou condições da promoção')),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('duracao_dias', models.PositiveIntegerField(default=30, help_text='Duração da assinatura em dias')),
                ('ativo', models.BooleanField(default=True, help_text='Exibir este plano na página de vendas')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição (menor aparece primeiro)')),
                ('eh_teste_gratis', models.BooleanField(default=False, help_text='Marca este como o plano de teste grátis')),
                ('eh_promocional', models.BooleanField(default=False, help_text='Marca este plano como promocional')),
                ('validade_promocao', models.DateTimeField(blank=True, help_text='Data/hora limite da promoção. Após essa data o plano não aparece mais (se promocional).', null=True)),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'ordering': ['ordem', 'preco'],
            },
        ),
    ]
