# Generated by Django 5.2 on 2026-06-11 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0009_alter_dadospaciente_antecedentepf_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evolucao',
            options={'permissions': [('pode_excluir_evolucao', 'Pode excluir evoluções')]},
        ),
    ]
