# Generated by Django 5.2 on 2026-06-28 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0010_alter_evolucao_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadospaciente',
            name='antecedentepf',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='dadospaciente',
            name='diagnostico',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='dadospaciente',
            name='exame_fisico',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='dadospaciente',
            name='exames_complementares',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='dadospaciente',
            name='hma',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='dadospaciente',
            name='hpp',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='dadospaciente',
            name='plano_terapeutico',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='dadospaciente',
            name='qp',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='endereco',
            field=models.CharField(max_length=255),
        ),
    ]
