# Generated by Django 5.2 on 2026-04-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0004_perfilprofissional_nomeclinica'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilprofissional',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='perfilprofissional',
            name='whatsapp',
            field=models.BooleanField(default=False),
        ),
    ]
