# Generated by Django 5.2 on 2026-06-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0005_perfilprofissional_telefone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilprofissional',
            name='assinatura',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/'),
        ),
    ]
