# Generated by Django 5.2 on 2026-06-11 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0006_perfilprofissional_assinatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilprofissional',
            name='pode_excluir_evolucoes',
            field=models.BooleanField(default=False, verbose_name='Pode excluir evoluções'),
        ),
    ]
