# Generated by Django 5.2 on 2026-06-28 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0008_alter_ativacao_user_alteracaoemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilprofissional',
            name='logotipo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='logos_profissionais/'),
        ),
    ]
